#!/bin/sh

NUTZER="user"
HOMED="/home/${NUTZER}"
export PKG_PATH=http://ftp.fau.de/pub/OpenBSD/snapshots/packages/amd64/
create directories(){
mkdir -p "${HOMED}/test"
mkdir -p "${HOMED}/.config/fish/functions"
mkdir -p "${HOMED}/.config/mpv"
mkdir -p "${HOMED}/.config/ranger"
mkdir -p "${HOMED}/Downloads/software_sources"
mkdir -p "${HOMED}/.newsbeuter"
}

pkg_add git curl

get_zsh(){
	pkg_add zsh
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
	chsh -s /usr/local/zsh ${NUTZER}
	mkdir -p ${HOMED}/.oh-my-zsh/custom/themes
	curl -o - https://raw.githubusercontent.com/denysdovhan/spaceship-zsh-theme/master/install.zsh | zsh

}

get_dotfiles(){
cd ${HOMED}/Downloads
git clone https://github.com/RobertPa/dotfiles

curl -Lo ${HOMED}/.config/fish/functions/fisher.fish --create-dirs https://git.io/fisher

cd dotfiles
cp -i ./xinitrc ${HOMED}/.xinitrc
cp -i ./vimrc ${HOMED}/.vimrc
cp -i ./mpv.conf ${HOMED}/.config/mpv
cp -i ./spectrwm.conf ${HOMED}/.spectrwm.conf
cp -i ./Xresources ${HOMED}/.Xressources
cp -i ./capsswitch ${HOMED}/.capsswitch
cp -i ./zshrc ${HOMED}/.zshrc
cp ./functions/* ${HOMED}/.config/fish/functions
}

source_trees(){
user mod -G wsrc $NUTZER
cd /usr
mkdir -p   xenocara ports src
chgrp wsrc xenocara ports
chmod 775  xenocara ports
cvs -qd anoncvs@anoncvs.ca.openbsd.org:/cvs get -P src
cvs -qd anoncvs@anoncvs.ca.openbsd.org:/cvs get -P ports
cvs -qd anoncvs@anoncvs.ca.openbsd.org:/cvs get -P xenocara
}

doas_config(){
echo " 
permit persist keepenv :wheel
permit nopass keepenv root
permit nopass ${NUTZER} as root cmd mount
permit nopass ${NUTZER} as root cmd umount
permit nopass ${NUTZER} as root cmd reboot
permit nopass ${NUTZER} as root cmd halt"
}

pkg_add -l ${HOMED}/Downloads/dotfiles/basic_pkgs_openbsd

#vim-plug for neovim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
cp ${HOMED}/Downloads/dotfiles/init.vim ${HOMED}/.config/nvim/

#cd ${HOMED}/Downloads/software_sources
#git clone https://github.com/neeasade/xst
#cd xst
#make && make install

cd ${HOMED}/Downloads/software_sources
git clone https://github.com/soimort/translate-shell
cd translate-shell/
make && make install

fw_update -a

chown -R $NUTZER:$NUTZER ${HOMED}


